[theme]
primaryColor = "#4bff90ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#080808ff"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
